### PR TITLE
Working WASIX API

### PR DESCRIPTION
**Pull request by WanderLanz**
Before any consideration for merging, compatibility with `@wasmer/wasi` is broken, so the package under `@wasmer/wasix` to prevent accidental breakage. No consideration was made to make it 1-1 compatible.

I tried to stay as close as possible to `wasi-web` in hopes of being able to just copy/sync in the future.

## Added

- networking via fetch
- threading via workers
- TTY (immutable unless handled by JavaScript consumer)
- dynamic NodeJS polyfills for crypto, fetch, & Worker
- WasiConfig options "concurrency" (1-16) & "tty" (starting TTY State)
- console_error_panic_hook, wee_alloc, & tracing features

## Changed

- IO now using WritableStream/ReadableStream for more interactivity.
- wasm-pack wasm artifact is not inlined, node uses node:fs to load instead of fetch
- file Read API now more closely resembles WebAPI (Blob/File)
- init() arguments and behavior, to avoid problems with Workers using init()
- enabled Reference Types, enabled WeakRefs, added -Zbuild-std=panic_abort,std to scripts
- Modernized browserlist, will not be as compatible with outdated or LTS browsers
- some simplifying naming changes

### Todo

- [ ] create tests for new API
- [x] update examples
- [x] update documentation
- [x] fix CI for nightly requirement

### CODE REVIEW

**Comment by WanderLanz** [comment]
Having trouble getting tests to work, wasix-libc is importing "wasi" "thread-start" instead of "wasix_32v1" "thread_start". I'll have to wait for someone to get back to me on that before I can make tests with threads.

Is there perhaps a way to use a custom runtime for the integration tests in main repo? I'm not familiar with the wasmer workspace so I'm kind of just shooting in the dark here.

**Comment by syrusakbary** [comment]
Hey @WanderLanz , this PR is awesome work.

We want to add some of the bits of it back into the Wasmer repo (so it's available for anyone trying to compile Wasmer to the browser), but most of the glue things that you created look great. Really good work on updating everything, including reworking current tests.

We'll probably rebase your PR with the new one once things get merged upstream.

**Comment by WanderLanz** [comment]
@syrusakbary Awesome! I'm glad it'll be of help. Bundling was half the headache, as usual, so hopefully everything goes smoothly for everyone.

**Comment by WanderLanz** [comment]
Hey just checking back in, it seems like @`Michael-F-Bryan already got the useful parts in the wasix branch, I'll go ahead and close this. Thank you!

**Pull request closed without merging**
