### PR TITLE
Add mapping to --dir option

### PR DESCRIPTION
**Pull request by mischnic**
Make it possible to provide a mapping using the dir option: `wasmer-js run test.wasm --dir=/::/some/host/folder`. Or should this be a different flag (`--mapdir`?)

### CODE REVIEW

**Comment by syrusakbary** [comment]
@mischnic let's use `--mapdir` (and one `:` to separate directories, instead of two `::`).

**Comment by mischnic** [comment]
Updated,
but I didn't find a way to change this "example" in the usage info to something like `wasmDir:hostDir`:
```
OPTIONS
  -h, --help       show CLI help
  --dir=dir
  --mapdir=mapdir
           ^^^^^^
```

**Comment by syrusakbary** [comment]
Looks good. Once tests pass we should be good to merge.

Note, there's seem to be a styling issue on the js:
```
@wasmer/cli: /home/vsts/work/1/s/packages/cli/src/commands/run.ts:22:5
@wasmer/cli: ERROR: 22:5  object-literal-sort-keys  The key 'help' is not sorted alphabetically
@wasmer/cli: npm ERR! code ELIFECYCLE
@wasmer/cli: npm ERR! errno 2
@wasmer/cli: npm ERR! @wasmer/cli@0.5.1 posttest: `tslint -p test -t stylish`
@wasmer/cli: npm ERR! Exit status 2```

This can be solved by moving the mapdir field definition after help :)

**Comment by mischnic** [comment]
🎉  
The tests pass now

**Comment by syrusakbary** [comment]
Merged :)

**Pull request merged**
